library(readr)
library(stringr)
library(glue)
library(tesseract)
library(googlesheets4)
library(lubridate)
library(janitor)
library(ggplot2)
library(patchwork)
library(forcats)
library(tabulizer)
library(data.table)
library(dplyr)
library(rvest)
library(here)
library(tidyr)
library(haven)
library(purrr)
library(magick)
library(lubridate)
library(xml2)
library(webshot)
library(crimeutils)
library(DT)
library(ggplot2)

make_pretty_date <- function(date) {
  return(paste0(lubridate::month(date, label = TRUE, abbr = FALSE),
                " ", lubridate::day(date), ", ", lubridate::year(date)))
}
